### ISSUE TITLE
Update dependencies / whole build structure

### ISSUE THREAD

**Issue by svetozarsadecky** [odyzeo/form-checkbox#3]
This is necessary because currently only with node ver. 8+ the dependencies can be installed; 
Node 12+ will throw errors 

```
> fsevents@1.2.7 install /Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v72-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and node@12.11.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@12.11.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.


No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.


No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.


gyp: No Xcode or CLT version detected!
gyp: No Xcode or CLT version detected!
gypgyp ERR!  ERR!configure error  
configure error 
gypgyp  ERR!ERR!  stackstack Error: `gyp` failed with exit code: 1
 Error: `gyp` failed with exit code: 1
gypgyp  ERR!ERR!  stackstack     at ChildProcess.onCpExit (/Users/svetozarsadecky/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
     at ChildProcess.onCpExit (/Users/svetozarsadecky/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gypgyp  ERR!ERR!  stackstack     at ChildProcess.emit (events.js:210:5)
     at ChildProcess.emit (events.js:210:5)
gypgyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gypgyp  ERR!ERR!  SystemSystem Darwin 19.2.0
 Darwin 19.2.0
gypgyp  ERR!ERR!  commandcommand "/Users/svetozarsadecky/.nvm/versions/node/v12.11.1/bin/node" "/Users/svetozarsadecky/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi"
 "/Users/svetozarsadecky/.nvm/versions/node/v12.11.1/bin/node" "/Users/svetozarsadecky/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi"
gypgyp  ERR!ERR!  cwdcwd /Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents
 /Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents
gypgyp  ERR!ERR!  node -vnode -v v12.11.1
 v12.11.1
gypgyp  ERR!ERR!  node-gyp -vnode-gyp -v v5.0.5
 v5.0.5
gypgyp  ERR!ERR!  not oknot ok 
 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/svetozarsadecky/.nvm/versions/node/v12.11.1/bin/node /Users/svetozarsadecky/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/Users/svetozarsadecky/.nvm/versions/node/v12.11.1/bin/node" "/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents
node-pre-gyp ERR! node -v v12.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/Users/svetozarsadecky/.nvm/versions/node/v12.11.1/bin/node /Users/svetozarsadecky/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/svetozarsadecky/Sites/form-checkbox/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)
added 1431 packages in 12.43s
```

**Comment by odyzeo** [comment]
Fixed in v2
